server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8197/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8196/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-carts
            - JwtAuthFilter
        - id: auth-servis
          uri: http://localhost:8198/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-auth
            - JwtAuthFilter
        - id: stat-service
          uri: http://localhost:8190/
          predicates:
            - Path=/stat/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-stat
            - JwtAuthFilter
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
